### ISSUE TITLE
Improve Visualization of Regular Expressions

### ISSUE THREAD

**Issue by trieloff** [adobe/jsonschema2md#27]
Maybe we can use something like this: https://www.npmjs.com/package/@kogai/regex-railroad-diagram

To visualize complex regular expressions.

**Comment by alainlecluse** [comment]
@trieloff  is this still an active wish?

**Comment by trieloff** [comment]
I think it would be cool, but I'm not sure how practical it is

**Comment by alainlecluse** [comment]
It will give the reader a quick and clear overview of the regex. But the descriptive explanation of regexr.com gives you way more information. 
for example [regexr.com](https://regexr.com/?expression=%5Ev%5Cd%2B%24) vs. [regexper.com](https://regexper.com/#%5E%5Ba-z0-9_.-%5D%2B%24i)

When viewing the enhancement, I was really interested in the possible result. But that slightly changed when I saw the state of JS packages that transform regex into railroad diagrams. In a nutshell, there are none. The closest is [@kogai/vscode-regex-railroad-diagrams](https://github.com/kogai/vscode-regex-railroad-diagrams). It's a VS code plugin with excellent railroad-diagram output. The problem is that that the regex to railroad code is not a separate package.  
I don't think this project needs/wants to write an own a regex to railroad diagram parser.

**Comment by trieloff** [comment]
Agree. The let's close the issue until the situation changes.
